on:
  push:
    branches: main

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build
         
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.1
        with:
         server: ftp.mariful-islam.com
         username: testaccount@app.marifulislam.com
         password: ",JrL@mW1U^^#"
         dangerous-clean-slate: true
         local-dir: ./dist/
         timeout: 600000  
         debug: true
         ftp-passive: false
         transfer-mode: binary
